---
title: "Untitled"
author: "David Henderson"
date: "30/03/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(janitor)
library(gtools)
library(sf)
library(cowplot)

theme_set(theme_minimal(base_family = "Roboto",
                        base_size = 18) +
            theme(panel.grid.minor = element_blank()))
```

```{r}
presc <- data.table::fread("https://www.opendata.nhs.scot/dataset/84393984-14e9-4b0d-a797-b288db64d088/resource/fa276ad2-669a-472f-9c47-809f199fae21/download/pitc201912.csv")

geog <- data.table::fread("https://www.opendata.nhs.scot/dataset/9f942fdb-e59e-44f5-b534-d6e17229cc7b/resource/395476ab-0720-4740-be07-ff4467141352/download/geography_codes_and_labels_dz2011_10012020.csv") %>% 
  clean_names %>% 
  select(hb2014, hb2014name) %>% 
  distinct(hb2014, hb2014name)

pop <- data.table::fread("https://www.opendata.nhs.scot/dataset/7f010430-6ce1-4813-b25c-f7f335bdc4dc/resource/27a72cc8-d6d8-430c-8b4f-3109a9ceadb1/download/hb2014_pop_est_01072019.csv") %>% 
  mutate(Year = as.character(Year)) %>% 
  filter(Year == "2018" & HB2014 != "S92000003") 

hb_pop <- 
  pop %>% 
  select(HB2014, AllAges) %>% 
  group_by(HB2014) %>% 
  summarise(total_pop = sum(AllAges)) %>% 
  clean_names
```


```{r}
presc_resp <- 
  presc %>% 
  clean_names %>% 
  rename(hb2014 = hbt2014) %>% 
  filter(str_detect(bnf_item_code, "^03")) %>%  
  left_join(., geog) %>% 
  left_join(., hb_pop) %>% 
  group_by(hb2014) %>% 
  mutate(n_gp = n_distinct(gp_practice),
         resp = sum(paid_quantity)/total_pop) 


presc_resp %>% 
  distinct(hb2014, resp, .keep_all = TRUE) %>% 
  ggplot(aes(reorder(hb2014name, -resp), resp)) +
  geom_col(fill = "#4477AA") +
  coord_flip() +
  labs(x = "", 
       y = "Number of paid respiratory items per head of population")
```

```{r}
final_tab <- 
  pop %>% 
  select(HB2014, Age70:Age90plus) %>% 
  mutate(pop_70plus = rowSums(.[2:22])) %>% 
  select(HB2014, pop_70plus) %>% 
  clean_names %>% 
  left_join(presc_resp, .) %>% 
  distinct(hb2014name, .keep_all = TRUE) %>% 
  mutate(frq70 = round(pop_70plus/total_pop * 100,1)) %>% 
  rename(id = hb2014name) %>% 
  mutate(id = str_replace_all(id, "NHS ", "")) %>% 
  ungroup

final_tab

final_tab %>% 
  ggplot(aes(frq70, resp)) +
  geom_point() +
  scale_x_continuous(limits = c(0, 15)) +
  scale_y_continuous(limits = c(0, 5))
```



```{r}
#generate tertiles
final_tab$age70tert <- quantcut(final_tab$frq70, q=3, labels=FALSE)
final_tab$resptert <- quantcut(final_tab$resp, q=3, labels=FALSE)

#save cutoffs
frq70_1 <- quantile(final_tab$frq70, probs=1/3, na.rm=TRUE)
frq70_2 <- quantile(final_tab$frq70, probs=2/3, na.rm=TRUE)
resp_1 <- quantile(final_tab$resp, probs=1/3, na.rm=TRUE)
resp_2 <- quantile(final_tab$resp, probs=2/3, na.rm=TRUE)

#generate 9-category index for map key
final_tab$key <- case_when(
  final_tab$age70tert==1 & final_tab$resptert==1 ~ 1,
  final_tab$age70tert==1 & final_tab$resptert==2 ~ 2,
  final_tab$age70tert==1 & final_tab$resptert==3 ~ 3,
  final_tab$age70tert==2 & final_tab$resptert==1 ~ 4,
  final_tab$age70tert==2 & final_tab$resptert==2 ~ 5,
  final_tab$age70tert==2 & final_tab$resptert==3 ~ 6,
  final_tab$age70tert==3 & final_tab$resptert==1 ~ 7,
  final_tab$age70tert==3 & final_tab$resptert==2 ~ 8,
  final_tab$age70tert==3 & final_tab$resptert==3 ~ 9
)

#fill in corresponding colours
final_tab$colour <- case_when(
  final_tab$key==1 ~ "#CABED0",
  final_tab$key==2 ~ "#BC7C5F",
  final_tab$key==3 ~ "#AE3A4E",
  final_tab$key==4 ~ "#89A1C8",
  final_tab$key==5 ~ "#806A8A",
  final_tab$key==6 ~ "#77324C",
  final_tab$key==7 ~ "#4885C1",
  final_tab$key==8 ~ "#435786",
  final_tab$key==9 ~ "#3f2949"
  
)

keydata <- final_tab %>%
  filter(!is.na(colour)) %>%
  group_by(age70tert, resptert) %>%
  summarise(RGB=unique(colour)) %>% 
  ungroup %>% 
  add_row(., age70tert = 1, resptert = 2, RGB = "#BC7C5F") %>% 
  add_row(., age70tert = 2, resptert = 1, RGB = "#89A1C8")

final_tab
```




```{r}
hb_shp <- read_sf("data/SG_NHS_HealthBoards_2019/SG_NHS_HealthBoards_2019.shp") %>% 
  rename(id = HBName)

final_tab <- 
  final_tab %>% 
  left_join(., hb_shp)
final_tab
```


```{r, fig.width=9, fig.height=12}
map <- 
  ggplot(final_tab) +
  geom_sf(aes(geometry = geometry,
              fill = colour), 
          alpha = 0.8,
          colour = 'white',
          size = 0.3) +
  scale_fill_identity() +
  annotate("text", x=50000, y=1000000, label="Purple areas mean\nhigher % of population over 70\nand high rates of\nprescribed respiratory drugs\nper capita", size=3.5) +
  annotate("text", x = 450000, y=950000, label= "Grey areas mean\n lower % of population over 70 and\nlower rates of prescribed\nrespiratory medicines per capita", size = 3.5) +
  geom_curve(aes(x=50000, y=960000, xend=100000, yend=900000),
             curvature=0.15, 
             arrow = arrow(angle = 30, type = "closed", length = unit(2, "mm"))) +
  geom_curve(aes(x=455000, y=910000, xend=400000, yend=820000), 
             curvature=-0.25,
             arrow = arrow(angle = 30, type = "closed", length = unit(2, "mm")))+
  expand_limits(x = 550000) +
  labs(title="Patterns of older people and respiratory prescribing",
       subtitle="by Scottish Health Board",
       caption="Data from opendata.nhs.scot & data.gov.uk\nplot by @_davidhen") +
  theme(axis.line=element_blank(), 
        axis.ticks=element_blank(), 
        axis.text=element_blank(),
        axis.title=element_blank(),
        panel.grid = element_blank())
map
```



```{r}
key <- ggplot(keydata)+
  geom_tile(aes(x=age70tert, y=resptert, fill=RGB))+
  scale_fill_identity()+
  labs(x = expression("Higher population % 70+" %->%  ""),
       y = expression("Higher respiratory prescriptions\n               per capita" %->%  "")) +
  # make font small enough
  theme(
    axis.title = element_text(size = 8),
    axis.line=element_blank(), 
    axis.ticks=element_blank(), 
    axis.text=element_blank())+
  # quadratic tiles
  coord_fixed()

key
```




```{r, fig.width=9, fig.height=12}
final <- 
  ggdraw()+
  draw_plot(map, 0,0,1,1)+
  draw_plot(key, 0.03,0.45,0.29,0.73)
final
```



```{r}
ggsave("age_resp_plot.png", final, width = 9, height = 12, dpi = 600)
```

